-- Seed Buildings
INSERT INTO buildings (id, name, code, category, floors, entrance_node_ids, description, open_hours) VALUES
(1, 'Computer Science & Engineering Block', 'CSE', 'academic', '0,1,2', '9', 'Department of Computer Science, AI Lab, Data Engineering & Cyber Security.', '08:00 AM - 08:00 PM'),
(2, 'Electronics & Communication Block', 'ECE', 'academic', '0,1', '18', 'VLSI Labs, Embedded Systems, and the APJ Abdul Kalam Seminar Hall.', '08:00 AM - 07:00 PM'),
(3, 'Central University Library', 'LIB', 'academic', '0,1', '6', '3-story knowledge repository with 80,000+ volumes, digital archives, and quiet study pods.', '07:30 AM - 10:00 PM'),
(4, 'Dr. Vikram Sarabhai Grand Auditorium', 'AUD', 'amenity', '0', '23,25', '1,500-seat multi-tier acoustic auditorium for symposiums and convocations.', '09:00 AM - 09:00 PM'),
(5, 'Campus Student Center & Food Court', 'CAN', 'amenity', '0', '20', 'Dining quad with multi-cuisine food stalls, cafe, and student lounge.', '07:00 AM - 11:00 PM'),
(6, 'Campus Health Center & Emergency Triage', 'MED', 'emergency', '0', '22', '24/7 medical station with doctor on duty, emergency triage, pharmacy, and ambulance bay.', '24 Hours Open'),
(7, 'Campus Security Headquarters', 'SEC', 'emergency', '0', '2', 'Central surveillance, ID card issuance, emergency dispatch, and lost & found unit.', '24 Hours Open'),
(8, 'North Residential Hostels & Quad', 'HST', 'residential', '0,1,2,3', '26', 'Undergraduate student housing quad with recreational courts and laundry hub.', 'Resident Access 24h');

-- Seed Navigation Nodes
INSERT INTO navigation_nodes (id, name, building_id, building_name, floor, type, x, y, is_accessible, is_emergency, emergency_type, description) VALUES
(1, 'Main Campus Gate', NULL, NULL, 0, 'gate', 120, 560, TRUE, FALSE, NULL, 'Primary security checkpoint & visitor arrival point'),
(2, 'Security Command Office', 7, 'Campus Security Headquarters', 0, 'emergency', 190, 530, TRUE, TRUE, 'security', 'Emergency dispatch & safety personnel'),
(3, 'South Quad Junction', NULL, NULL, 0, 'junction', 290, 500, TRUE, FALSE, NULL, 'Major pedestrian walkway crossing south campus'),
(4, 'West Visitor Parking', NULL, NULL, 0, 'parking', 120, 390, TRUE, FALSE, NULL, 'EV charging points & visitor parking lots'),
(5, 'Central Campus Plaza & Fountain', NULL, NULL, 0, 'junction', 440, 430, TRUE, FALSE, NULL, 'Main gathering circle with benches and campus directory'),
(6, 'Library Front Plaza', 3, 'Central University Library', 0, 'building_entrance', 440, 310, TRUE, FALSE, NULL, 'Entrance plaza to Central Library'),
(7, 'Library Ground Circulation', 3, 'Central University Library', 0, 'library', 440, 250, TRUE, FALSE, NULL, 'Circulation desk, return kiosks, digital search'),
(8, 'Library 1st Floor Quiet Hall', 3, 'Central University Library', 1, 'library', 440, 190, TRUE, FALSE, NULL, 'Quiet study pods and research journals'),
(9, 'CSE Block Main Entrance', 1, 'Computer Science & Engineering Block', 0, 'building_entrance', 610, 460, TRUE, FALSE, NULL, 'Glass doors leading to Computer Science complex'),
(10, 'CSE Ground Floor Atrium', 1, 'Computer Science & Engineering Block', 0, 'junction', 670, 460, TRUE, FALSE, NULL, 'Central indoor atrium connecting stairs and elevators'),
(11, 'CSE Central Stairwell', 1, 'Computer Science & Engineering Block', 0, 'stairs', 720, 425, FALSE, FALSE, NULL, 'Indoor stairs to 1st & 2nd floors'),
(12, 'CSE ADA Accessible Elevator', 1, 'Computer Science & Engineering Block', 0, 'elevator', 720, 495, TRUE, FALSE, NULL, 'Wheelchair-certified high-speed elevator'),
(13, 'CSE 1st Floor Landing', 1, 'Computer Science & Engineering Block', 1, 'junction', 770, 460, TRUE, FALSE, NULL, 'First floor foyer outside departmental labs'),
(14, 'AI & Machine Learning Lab', 1, 'Computer Science & Engineering Block', 1, 'room', 860, 410, TRUE, FALSE, NULL, 'Room 101 - GPU cluster, robotics rigs, neural net testing'),
(15, 'Computer Lab 102', 1, 'Computer Science & Engineering Block', 1, 'room', 860, 510, TRUE, FALSE, NULL, 'Room 102 - 60 Linux workstations, compiler tools'),
(16, 'CSE 2nd Floor Landing', 1, 'Computer Science & Engineering Block', 2, 'junction', 770, 460, TRUE, FALSE, NULL, 'Second floor foyer for specialized research centers'),
(17, 'Robotics & IoT Innovation Lab', 1, 'Computer Science & Engineering Block', 2, 'room', 860, 460, TRUE, FALSE, NULL, 'Room 205 - ROS drones, autonomous vehicle testbed'),
(18, 'ECE Block Main Entrance', 2, 'Electronics & Communication Block', 0, 'building_entrance', 610, 620, TRUE, FALSE, NULL, 'Ground entry for ECE laboratories & faculty'),
(19, 'Seminar Hall (Abdul Kalam Hall)', 2, 'Electronics & Communication Block', 0, 'auditorium', 730, 620, TRUE, FALSE, NULL, '250-seat state-of-the-art multimedia presentation hall'),
(20, 'Canteen & Food Court Plaza', 5, 'Campus Student Center & Food Court', 0, 'canteen', 310, 260, TRUE, FALSE, NULL, 'Outdoor cafe terrace and student dining'),
(21, 'Canteen Indoor Dining Hall', 5, 'Campus Student Center & Food Court', 0, 'canteen', 260, 220, TRUE, FALSE, NULL, 'Meal counters, juice corner, coffee bar'),
(22, 'Medical Room & Triage Station', 6, 'Campus Health Center & Emergency Triage', 0, 'emergency', 220, 320, TRUE, TRUE, 'medical', 'First-aid, emergency stretchers, doctor on duty'),
(23, 'Auditorium Main Steps Entrance', 4, 'Dr. Vikram Sarabhai Grand Auditorium', 0, 'building_entrance', 580, 240, FALSE, FALSE, NULL, 'Wide exterior marble staircase to auditorium'),
(24, 'Auditorium Main Stage Hall', 4, 'Dr. Vikram Sarabhai Grand Auditorium', 0, 'auditorium', 680, 210, TRUE, FALSE, NULL, 'Main theater seating and stage'),
(25, 'Auditorium ADA Accessible Ramp Entrance', 4, 'Dr. Vikram Sarabhai Grand Auditorium', 0, 'building_entrance', 570, 280, TRUE, FALSE, NULL, 'Gentle gradient ADA ramp for barrier-free access'),
(26, 'North Hostel Quad Walkway', 8, 'North Residential Hostels & Quad', 0, 'facility', 330, 110, TRUE, FALSE, NULL, 'Pathway to residential blocks A, B & C'),
(27, 'Emergency Exit North Gate', NULL, NULL, 0, 'emergency', 620, 90, TRUE, TRUE, 'exit', 'Perimeter emergency evacuation gate & fire lane'),
(28, 'Emergency Police Help Point SOS', NULL, NULL, 0, 'emergency', 470, 550, TRUE, TRUE, 'police', 'Direct 1-button SOS intercom to security & local police'),
(29, 'East Quad Shaded Bypass Walkway', NULL, NULL, 0, 'junction', 520, 510, TRUE, FALSE, NULL, 'Paved canopy walkway offering alternate detour past central lawn');

-- Seed Paths
INSERT INTO navigation_paths (id, source_node_id, destination_node_id, distance, is_indoor, is_stairs, is_elevator, is_accessible, is_blocked, blocked_reason, floor, bidirectional) VALUES
(101, 1, 2, 75, FALSE, FALSE, FALSE, TRUE, FALSE, NULL, 0, TRUE),
(102, 1, 3, 180, FALSE, FALSE, FALSE, TRUE, FALSE, NULL, 0, TRUE),
(103, 1, 4, 175, FALSE, FALSE, FALSE, TRUE, FALSE, NULL, 0, TRUE),
(104, 2, 3, 110, FALSE, FALSE, FALSE, TRUE, FALSE, NULL, 0, TRUE),
(105, 3, 5, 140, FALSE, FALSE, FALSE, TRUE, FALSE, NULL, 0, TRUE),
(106, 3, 22, 190, FALSE, FALSE, FALSE, TRUE, FALSE, NULL, 0, TRUE),
(107, 4, 22, 120, FALSE, FALSE, FALSE, TRUE, FALSE, NULL, 0, TRUE),
(108, 22, 20, 110, FALSE, FALSE, FALSE, TRUE, FALSE, NULL, 0, TRUE),
(109, 20, 21, 60, TRUE, FALSE, FALSE, TRUE, FALSE, NULL, 0, TRUE),
(110, 20, 6, 140, FALSE, FALSE, FALSE, TRUE, FALSE, NULL, 0, TRUE),
(111, 5, 6, 120, FALSE, FALSE, FALSE, TRUE, FALSE, NULL, 0, TRUE),
(112, 5, 9, 130, FALSE, FALSE, FALSE, TRUE, FALSE, NULL, 0, TRUE),
(113, 3, 29, 240, FALSE, FALSE, FALSE, TRUE, FALSE, NULL, 0, TRUE),
(114, 29, 9, 110, FALSE, FALSE, FALSE, TRUE, FALSE, NULL, 0, TRUE),
(115, 5, 29, 115, FALSE, FALSE, FALSE, TRUE, FALSE, NULL, 0, TRUE),
(116, 3, 28, 190, FALSE, FALSE, FALSE, TRUE, FALSE, NULL, 0, TRUE),
(117, 28, 18, 160, FALSE, FALSE, FALSE, TRUE, FALSE, NULL, 0, TRUE),
(118, 9, 18, 160, FALSE, FALSE, FALSE, TRUE, FALSE, NULL, 0, TRUE),
(119, 6, 7, 60, TRUE, FALSE, FALSE, TRUE, FALSE, NULL, 0, TRUE),
(120, 7, 8, 70, TRUE, FALSE, TRUE, TRUE, FALSE, NULL, 0, TRUE),
(121, 9, 10, 60, TRUE, FALSE, FALSE, TRUE, FALSE, NULL, 0, TRUE),
(122, 10, 11, 55, TRUE, FALSE, FALSE, TRUE, FALSE, NULL, 0, TRUE),
(123, 10, 12, 65, TRUE, FALSE, FALSE, TRUE, FALSE, NULL, 0, TRUE),
(124, 11, 13, 60, TRUE, TRUE, FALSE, FALSE, FALSE, NULL, 0, TRUE),
(125, 12, 13, 85, TRUE, FALSE, TRUE, TRUE, FALSE, NULL, 0, TRUE),
(126, 13, 14, 95, TRUE, FALSE, FALSE, TRUE, FALSE, NULL, 1, TRUE),
(127, 13, 15, 95, TRUE, FALSE, FALSE, TRUE, FALSE, NULL, 1, TRUE),
(128, 13, 16, 60, TRUE, TRUE, FALSE, FALSE, FALSE, NULL, 1, TRUE),
(129, 12, 16, 110, TRUE, FALSE, TRUE, TRUE, FALSE, NULL, 0, TRUE),
(130, 16, 17, 90, TRUE, FALSE, FALSE, TRUE, FALSE, NULL, 2, TRUE),
(131, 18, 19, 120, TRUE, FALSE, FALSE, TRUE, FALSE, NULL, 0, TRUE),
(132, 6, 23, 150, FALSE, TRUE, FALSE, FALSE, FALSE, NULL, 0, TRUE),
(133, 6, 25, 180, FALSE, FALSE, FALSE, TRUE, FALSE, NULL, 0, TRUE),
(134, 5, 25, 195, FALSE, FALSE, FALSE, TRUE, FALSE, NULL, 0, TRUE),
(135, 23, 24, 75, TRUE, FALSE, FALSE, FALSE, FALSE, NULL, 0, TRUE),
(136, 25, 24, 85, TRUE, FALSE, FALSE, TRUE, FALSE, NULL, 0, TRUE),
(137, 20, 26, 160, FALSE, FALSE, FALSE, TRUE, FALSE, NULL, 0, TRUE),
(138, 6, 26, 210, FALSE, FALSE, FALSE, TRUE, FALSE, NULL, 0, TRUE),
(139, 26, 27, 290, FALSE, FALSE, FALSE, TRUE, FALSE, NULL, 0, TRUE),
(140, 24, 27, 160, FALSE, FALSE, FALSE, TRUE, FALSE, NULL, 0, TRUE);

-- Seed Facilities
INSERT INTO facilities (id, name, code, node_id, building_id, building_name, floor, department, category, features, status, description) VALUES
(1, 'AI & Machine Learning Research Lab', 'LAB-AI-101', 14, 1, 'Computer Science & Engineering Block', 1, 'Computer Science & Engineering', 'lab', 'High-end GPU Servers, Computer Vision rigs, Robotics bench, Air Conditioned', 'open', 'Premier research lab for machine learning, neural networks, and computer vision projects.'),
(2, 'High Performance Computer Lab 102', 'LAB-CS-102', 15, 1, 'Computer Science & Engineering Block', 1, 'Computer Science & Engineering', 'lab', '60 Linux Workstations, Dual Monitors, Fiber Gigabit LAN, Smart Screen', 'open', 'General programming lab for systems, networking, and distributed algorithms.'),
(3, 'Robotics & IoT Innovation Center', 'LAB-ROB-205', 17, 1, 'Computer Science & Engineering Block', 2, 'Computer Science & Robotics', 'lab', '3D Printers, Drone Testing Cage, Soldering Stations, Oscilloscopes', 'open', 'Multi-disciplinary robotics workshop and drone telemetry center.'),
(4, 'Central University Library - Reading Hall', 'LIB-HALL-10', 8, 3, 'Central University Library', 1, 'University Library Services', 'library', 'Silent Study Zones, Reference Section, Power Outlets at all desks, High-Speed Wi-Fi', 'open', 'Comprehensive physical reference collection with 400 silent study desks.'),
(5, 'Campus Health Center & Emergency Triage Room', 'MED-EMERGENCY', 22, 6, 'Campus Health Center & Emergency Triage', 0, 'University Medical Services', 'medical', '24/7 Paramedics, Cardiac Defibrillator, Oxygen Supply, Immediate Ambulance Dispatch', 'open', 'Campus emergency medical station with triage beds, pharmacy, and ambulance bay.'),
(6, 'Campus Security Command & Lost & Found', 'SEC-HQ-01', 2, 7, 'Campus Security Headquarters', 0, 'Campus Safety & Vigilance', 'security', '24h Dispatch Console, Lost & Found Locker, CCTV Monitor Room, Emergency Patrols', 'open', 'Main campus security and dispatch hub located near the main entrance.'),
(7, 'Dr. Vikram Sarabhai Grand Auditorium Hall', 'AUD-MAIN-01', 24, 4, 'Dr. Vikram Sarabhai Grand Auditorium', 0, 'University Events & Cultural Affairs', 'auditorium', '1,500 Ergonomic Seats, Dolby Surround Sound, Acoustic Wall Paneling, ADA Wheelchair Ramps', 'open', 'Main venue for international conferences, hackathon ceremonies, and convocations.'),
(8, 'Campus Food Court & Dining Terrace', 'CAN-MAIN', 20, 5, 'Campus Student Center & Food Court', 0, 'Student Amenities Board', 'canteen', '6 Cuisine Outlets, Espresso Cafe, Fresh Juice Counter, Covered Outdoor Seating', 'open', 'Central student culinary hub with diverse hygienic food choices.'),
(9, 'APJ Abdul Kalam Seminar Hall', 'ECE-SEM-01', 19, 2, 'Electronics & Communication Block', 0, 'Electronics & Communication', 'auditorium', '250 Executive Seats, Dual Laser Projectors, Video Conferencing Pod, Smart Podium', 'open', 'Air-conditioned conference and guest lecture venue.'),
(10, 'West Visitor & Faculty Parking Area', 'PRK-WEST', 4, NULL, 'West Campus Zone', 0, 'Campus Facilities', 'parking', '120 Car Slots, 250 Two-Wheeler Slots, Level 2 EV Charging Stations, 24/7 Boom Barrier', 'open', 'Designated parking for visitors, guest speakers, faculty, and handicapped vehicles.'),
(11, 'North Hostel Quad & Student Living Complex', 'HST-NORTH-01', 26, 8, 'North Residential Hostels & Quad', 0, 'Student Housing', 'hostel', 'Wi-Fi Enabled Lounges, Mess Dining, Recreational Gym, Laundry Service', 'restricted', 'Undergraduate student residence hall with biometric entry.'),
(12, 'Emergency Exit North Gate', 'EXIT-NORTH', 27, NULL, 'North Perimeter', 0, 'Campus Safety', 'security', 'Panic Bar Door, Emergency Strobe Light, Fire Evacuation Muster Point', 'open', 'Perimeter emergency evacuation gate leading to secondary highway and muster point.');

-- Seed Emergency Locations
INSERT INTO emergency_locations (id, name, type, node_id, building_name, contact_number, description) VALUES
(1, 'Medical Room & Triage Station', 'medical', 22, 'Campus Health Center', '+1 (800) 555-0911 (Ext. 108)', 'Immediate physician care, ambulance standby, and trauma support.'),
(2, 'Security Command Headquarters', 'security', 2, 'Campus Security Office', '+1 (800) 555-0999 (Ext. 100)', 'Dispatches quick response mobile patrol and monitors campus perimeter.'),
(3, 'Emergency Police Help Point SOS', 'police', 28, 'Central South Plaza SOS', '+1 (800) 555-HELP', 'High-visibility illuminated blue-light pillar with instant two-way speaker.'),
(4, 'Emergency Exit North Gate', 'exit', 27, 'North Perimeter Barrier', 'N/A (Evacuation Assembly Point B)', 'Direct assembly point with wide evacuation fire gate.');
